/**
 * Registro único de comandos.
 *
 * La barra de menú, los atajos de teclado y la paleta de comandos leen todos de
 * aquí. Si estuvieran por separado, añadir una acción obligaría a tocar tres sitios
 * y acabarían desincronizados, que es como el programa llegó a tener botones
 * cableados a elementos que ya no existían.
 *
 * Cada comando: id, menú al que pertenece, etiqueta, atajo por defecto y qué hace.
 *
 *   cuando: 'editor'  el atajo solo actúa con el foco en el editor de código. Fuera
 *                     (chat, buscadores), Ctrl+Z o Ctrl+A hacen lo normal del campo.
 *                     Desde el menú funciona siempre, sobre el último editor usado.
 *   nativo: true      el atajo lo resuelve el propio editor o el sistema (Ctrl+C,
 *                     Tab): se muestra en el menú, pero no se intercepta ni se reasigna.
 *
 * Los atajos siguen los de VS Code en Linux. Se evitan símbolos que en un teclado
 * español necesitan AltGr ([, ], \…): por eso plegar o ir al corchete van con letras.
 */
(function () {
    const seguro = (fn) => () => {
        try {
            const r = fn();
            if (r && typeof r.catch === 'function') r.catch(e => console.error('Comando falló:', e));
        } catch (e) { console.error('Comando falló:', e); }
    };
    const editor = () => window.editorMgr;
    const app = () => window.app;
    const ide = () => window.IDE;
    const accion = (id) => () => ide().accion(id);

    const COMANDOS = [
        // ---------------- Archivos ----------------
        { id: 'archivo.nuevoArchivo', menu: 'Archivos', label: 'Nuevo archivo…', accel: 'Ctrl+N',
          run: () => window.fileTreeMgr.createItem(false) },
        { id: 'archivo.nuevaCarpeta', menu: 'Archivos', label: 'Nueva carpeta…', accel: 'Ctrl+Shift+N',
          run: () => window.fileTreeMgr.createItem(true) },
        { id: 'archivo.abrirArchivo', menu: 'Archivos', label: 'Abrir archivo…', accel: 'Ctrl+O', separadorAntes: true,
          run: () => ide().irAArchivo() },
        { id: 'archivo.abrirCarpeta', menu: 'Archivos', label: 'Abrir carpeta de trabajo…', accel: 'Ctrl+K Ctrl+O',
          run: () => window.fileTreeMgr.openWorkspaceFolder() },
        { id: 'archivo.recientes', menu: 'Archivos', label: 'Abrir reciente…', accel: 'Ctrl+R',
          run: () => ide().abrirReciente() },
        { id: 'archivo.guardar', menu: 'Archivos', label: 'Guardar', accel: 'Ctrl+S', separadorAntes: true,
          run: () => app().saveCurrentFile() },
        { id: 'archivo.guardarComo', menu: 'Archivos', label: 'Guardar como…', accel: 'Ctrl+Shift+S',
          run: () => ide().guardarComo() },
        { id: 'archivo.guardarTodo', menu: 'Archivos', label: 'Guardar todo', accel: 'Ctrl+K S',
          run: () => ide().guardarTodo() },
        { id: 'archivo.autoguardado', menu: 'Archivos', label: 'Autoguardado',
          marcado: () => ide() && ide().autoguardadoActivo(),
          run: () => ide().alternarAutoguardado() },
        { id: 'archivo.revertir', menu: 'Archivos', label: 'Revertir archivo (descartar cambios)',
          run: () => ide().revertir() },
        { id: 'archivo.renombrar', menu: 'Archivos', label: 'Renombrar archivo…', separadorAntes: true,
          run: () => ide().renombrar() },
        { id: 'archivo.duplicar', menu: 'Archivos', label: 'Duplicar archivo',
          run: () => ide().duplicar() },
        { id: 'archivo.eliminar', menu: 'Archivos', label: 'Eliminar archivo…',
          run: () => ide().eliminar() },
        { id: 'archivo.copiarRuta', menu: 'Archivos', label: 'Copiar ruta', accel: 'Shift+Alt+C', separadorAntes: true,
          run: () => ide().copiarRuta(false) },
        { id: 'archivo.copiarRutaRelativa', menu: 'Archivos', label: 'Copiar ruta relativa', accel: 'Ctrl+K Ctrl+Shift+C',
          run: () => ide().copiarRuta(true) },
        { id: 'archivo.revelar', menu: 'Archivos', label: 'Mostrar en el explorador del sistema', accel: 'Ctrl+K R',
          run: () => ide().mostrarEnSistema() },
        { id: 'archivo.cerrarPestana', menu: 'Archivos', label: 'Cerrar pestaña', accel: 'Ctrl+W', separadorAntes: true,
          run: () => { const p = editor().getActivePath(); if (p) editor().closeTab(p); } },
        { id: 'archivo.cerrarOtras', menu: 'Archivos', label: 'Cerrar las demás pestañas',
          run: () => ide().cerrarOtras() },
        { id: 'archivo.cerrarGuardadas', menu: 'Archivos', label: 'Cerrar pestañas guardadas', accel: 'Ctrl+K U',
          run: () => ide().cerrarGuardadas() },
        { id: 'archivo.cerrarTodas', menu: 'Archivos', label: 'Cerrar todas las pestañas', accel: 'Ctrl+K Ctrl+W',
          run: () => ide().cerrarTodas() },
        { id: 'archivo.reabrir', menu: 'Archivos', label: 'Reabrir pestaña cerrada', accel: 'Ctrl+Shift+T',
          run: () => ide().reabrirCerrada() },
        { id: 'archivo.exportarPdf', menu: 'Archivos', label: 'Exportar carpeta a PDF…', accel: 'Ctrl+Shift+E', separadorAntes: true,
          run: () => window.workArea.abrirHerramienta('modal-pdf-exporter', 'Exportar PDF', 'fa-file-pdf') },

        // ---------------- Edición ----------------
        { id: 'edicion.deshacer', menu: 'Edición', label: 'Deshacer', accel: 'Ctrl+Z', cuando: 'editor',
          run: accion('undo') },
        { id: 'edicion.rehacer', menu: 'Edición', label: 'Rehacer', accel: 'Ctrl+Y', cuando: 'editor',
          run: accion('redo') },
        { id: 'edicion.cortar', menu: 'Edición', label: 'Cortar', accel: 'Ctrl+X', nativo: true, separadorAntes: true,
          run: () => ide().portapapeles('cortar') },
        { id: 'edicion.copiar', menu: 'Edición', label: 'Copiar', accel: 'Ctrl+C', nativo: true,
          run: () => ide().portapapeles('copiar') },
        { id: 'edicion.pegar', menu: 'Edición', label: 'Pegar', accel: 'Ctrl+V', nativo: true,
          run: () => ide().portapapeles('pegar') },
        { id: 'edicion.buscar', menu: 'Edición', label: 'Buscar', accel: 'Ctrl+F', cuando: 'editor', separadorAntes: true,
          run: accion('actions.find') },
        { id: 'edicion.reemplazar', menu: 'Edición', label: 'Reemplazar', accel: 'Ctrl+H', cuando: 'editor',
          run: accion('editor.action.startFindReplaceAction') },
        { id: 'edicion.buscarEnArchivos', menu: 'Edición', label: 'Buscar en archivos', accel: 'Ctrl+Shift+F',
          run: () => ide().abrirBusqueda({ reemplazar: false }) },
        { id: 'edicion.reemplazarEnArchivos', menu: 'Edición', label: 'Reemplazar en archivos', accel: 'Ctrl+Shift+H',
          run: () => ide().abrirBusqueda({ reemplazar: true }) },
        { id: 'edicion.comentar', menu: 'Edición', label: 'Comentar / descomentar línea', accel: 'Ctrl+/', cuando: 'editor', separadorAntes: true,
          run: accion('editor.action.commentLine') },
        { id: 'edicion.comentarioBloque', menu: 'Edición', label: 'Comentario de bloque', accel: 'Shift+Alt+A', cuando: 'editor',
          run: accion('editor.action.blockComment') },
        { id: 'edicion.formato', menu: 'Edición', label: 'Formatear documento', accel: 'Ctrl+Alt+F', cuando: 'editor',
          run: accion('editor.action.formatDocument') },
        { id: 'edicion.recortarEspacios', menu: 'Edición', label: 'Quitar espacios al final de línea', accel: 'Ctrl+K Ctrl+X', cuando: 'editor',
          run: accion('editor.action.trimTrailingWhitespace') },
        { id: 'edicion.copiarLineaAbajo', menu: 'Edición', label: 'Duplicar línea abajo', accel: 'Ctrl+Shift+Alt+Down', cuando: 'editor', separadorAntes: true,
          run: accion('editor.action.copyLinesDownAction') },
        { id: 'edicion.copiarLineaArriba', menu: 'Edición', label: 'Duplicar línea arriba', accel: 'Ctrl+Shift+Alt+Up', cuando: 'editor',
          run: accion('editor.action.copyLinesUpAction') },
        { id: 'edicion.moverLineaArriba', menu: 'Edición', label: 'Mover línea arriba', accel: 'Alt+Up', cuando: 'editor',
          run: accion('editor.action.moveLinesUpAction') },
        { id: 'edicion.moverLineaAbajo', menu: 'Edición', label: 'Mover línea abajo', accel: 'Alt+Down', cuando: 'editor',
          run: accion('editor.action.moveLinesDownAction') },
        { id: 'edicion.eliminarLinea', menu: 'Edición', label: 'Eliminar línea', accel: 'Ctrl+Shift+K', cuando: 'editor',
          run: accion('editor.action.deleteLines') },
        { id: 'edicion.sangrar', menu: 'Edición', label: 'Aumentar sangría', accel: 'Tab', nativo: true, separadorAntes: true,
          run: accion('editor.action.indentLines') },
        { id: 'edicion.desangrar', menu: 'Edición', label: 'Reducir sangría', accel: 'Shift+Tab', nativo: true,
          run: accion('editor.action.outdentLines') },
        { id: 'edicion.mayusculas', menu: 'Edición', label: 'Convertir a MAYÚSCULAS',
          run: accion('editor.action.transformToUppercase') },
        { id: 'edicion.minusculas', menu: 'Edición', label: 'Convertir a minúsculas',
          run: accion('editor.action.transformToLowercase') },
        { id: 'edicion.ordenarLineas', menu: 'Edición', label: 'Ordenar líneas (A→Z)',
          run: accion('editor.action.sortLinesAscending') },
        { id: 'edicion.plegar', menu: 'Edición', label: 'Plegar / desplegar bloque', accel: 'Ctrl+K Ctrl+.', cuando: 'editor', separadorAntes: true,
          run: accion('editor.toggleFold') },
        { id: 'edicion.plegarTodo', menu: 'Edición', label: 'Plegar todo', accel: 'Ctrl+K Ctrl+0', cuando: 'editor',
          run: accion('editor.foldAll') },
        { id: 'edicion.desplegarTodo', menu: 'Edición', label: 'Desplegar todo', accel: 'Ctrl+K Ctrl+J', cuando: 'editor',
          run: accion('editor.unfoldAll') },

        // ---------------- Selección ----------------
        { id: 'seleccion.todo', menu: 'Selección', label: 'Seleccionar todo', accel: 'Ctrl+A', cuando: 'editor',
          run: accion('editor.action.selectAll') },
        { id: 'seleccion.expandir', menu: 'Selección', label: 'Ampliar selección', accel: 'Shift+Alt+Right', cuando: 'editor',
          run: accion('editor.action.smartSelect.expand') },
        { id: 'seleccion.reducir', menu: 'Selección', label: 'Reducir selección', accel: 'Shift+Alt+Left', cuando: 'editor',
          run: accion('editor.action.smartSelect.shrink') },
        { id: 'seleccion.cursorArriba', menu: 'Selección', label: 'Añadir cursor arriba', accel: 'Shift+Alt+Up', cuando: 'editor', separadorAntes: true,
          run: accion('editor.action.insertCursorAbove') },
        { id: 'seleccion.cursorAbajo', menu: 'Selección', label: 'Añadir cursor abajo', accel: 'Shift+Alt+Down', cuando: 'editor',
          run: accion('editor.action.insertCursorBelow') },
        { id: 'seleccion.cursoresFinLinea', menu: 'Selección', label: 'Añadir cursores al final de las líneas', accel: 'Shift+Alt+I', cuando: 'editor',
          run: accion('editor.action.insertCursorAtEndOfEachLineSelected') },
        { id: 'seleccion.siguiente', menu: 'Selección', label: 'Añadir la siguiente coincidencia', accel: 'Ctrl+D', cuando: 'editor', separadorAntes: true,
          run: accion('editor.action.addSelectionToNextFindMatch') },
        { id: 'seleccion.todas', menu: 'Selección', label: 'Seleccionar todas las coincidencias', accel: 'Ctrl+Shift+L', cuando: 'editor',
          run: accion('editor.action.selectHighlights') },

        // ---------------- Vista ----------------
        { id: 'vista.paleta', menu: 'Vista', label: 'Paleta de comandos…', accel: 'Ctrl+Shift+P',
          run: () => window.menuBar.abrirPaleta() },
        { id: 'vista.modelo', menu: 'Vista', label: 'Panel Modelo', accel: 'Ctrl+L', separadorAntes: true,
          marcado: () => !(window.layoutMgr && window.layoutMgr.oculto.modelo),
          run: () => window.layoutMgr.togglePanel('modelo') },
        { id: 'vista.archivos', menu: 'Vista', label: 'Mostrar Archivos', accel: 'Ctrl+B',
          run: () => window.workArea.verEnModelo('archivos') },
        { id: 'vista.terminal', menu: 'Vista', label: 'Mostrar Consola', accel: 'Ctrl+J',
          run: () => window.workArea.abrir('consola') },
        { id: 'vista.buscar', menu: 'Vista', label: 'Mostrar Buscar', accel: 'Ctrl+K Ctrl+F',
          run: () => ide().abrirBusqueda({}) },
        { id: 'vista.modeloTab', menu: 'Vista', label: 'Sección Modelo: pestaña Modelo', accel: 'Ctrl+Alt+1',
          run: () => window.workArea.verEnModelo('modelo') },
        { id: 'vista.archivosTab', menu: 'Vista', label: 'Sección Modelo: pestaña Archivos', accel: 'Ctrl+Alt+2',
          run: () => window.workArea.verEnModelo('archivos') },
        { id: 'vista.editor', menu: 'Vista', label: 'Ir al Editor', accel: 'Ctrl+Alt+E', separadorAntes: true,
          run: () => window.workArea.activar('editor') },
        { id: 'vista.cuaderno', menu: 'Vista', label: 'Abrir vista de Cuaderno', accel: 'Ctrl+Alt+N',
          run: () => window.workArea.activar('editor') },
        { id: 'vista.dividir', menu: 'Vista', label: 'Abrir el archivo al lado', accel: 'Ctrl+\\',
          run: () => window.workArea.dividir() },
        { id: 'vista.dividirPaneles', menu: 'Vista', label: 'Dividir área de trabajo (Lado a lado)', accel: 'Ctrl+Alt+\\',
          run: () => window.workArea && window.workArea.abrirDivision() },
        { id: 'vista.intercambiarPaneles', menu: 'Vista', label: 'Intercambiar paneles (Izquierda ↔ Derecha)', accel: 'Alt+\\',
          run: () => window.workArea && window.workArea.intercambiarPaneles() },
        { id: 'vista.moverAlOtroLado', menu: 'Vista', label: 'Mover pestaña actual al otro lado', accel: 'Alt+Shift+\\',
          run: () => {
              if (window.workArea) {
                  const foco = window.workArea.ladoFoco || 'izq';
                  const activa = window.workArea.paneles[foco].activa;
                  if (activa) window.workArea.moverALado(activa, foco === 'izq' ? 'der' : 'izq');
              }
          } },
        // Ctrl+Alt+←/→ (el de VS Code) lo usa GNOME para cambiar de escritorio: no llegaría a Prig
        { id: 'vista.moverVentanaDerecha', menu: 'Vista', label: 'Mover la ventana al panel derecho', accel: 'Ctrl+K Ctrl+Right',
          run: () => window.workArea && window.workArea.moverActivaA('der') },
        { id: 'vista.moverVentanaIzquierda', menu: 'Vista', label: 'Mover la ventana al panel izquierdo', accel: 'Ctrl+K Ctrl+Left',
          run: () => window.workArea && window.workArea.moverActivaA('izq') },
        { id: 'vista.enfocarPanelIzquierdo', menu: 'Vista', label: 'Ir al panel izquierdo', accel: 'Ctrl+K Ctrl+1',
          run: () => window.workArea && window.workArea.enfocarPanel('izq') },
        { id: 'vista.enfocarPanelDerecho', menu: 'Vista', label: 'Ir al panel derecho', accel: 'Ctrl+K Ctrl+2',
          run: () => window.workArea && window.workArea.enfocarPanel('der') },
        { id: 'vista.ventanaSiguiente', menu: 'Vista', label: 'Ventana siguiente', accel: 'Ctrl+Alt+PageDown',
          run: () => window.workArea && window.workArea.ventanaSiguiente(+1) },
        { id: 'vista.ventanaAnterior', menu: 'Vista', label: 'Ventana anterior', accel: 'Ctrl+Alt+PageUp',
          run: () => window.workArea && window.workArea.ventanaSiguiente(-1) },
        { id: 'vista.pestanaDerecha', menu: 'Vista', label: 'Correr la ventana un lugar a la derecha', accel: 'Ctrl+Shift+PageDown',
          run: () => window.workArea && window.workArea.moverPestana(+1) },
        { id: 'vista.pestanaIzquierda', menu: 'Vista', label: 'Correr la ventana un lugar a la izquierda', accel: 'Ctrl+Shift+PageUp',
          run: () => window.workArea && window.workArea.moverPestana(-1) },
        { id: 'vista.cerrarDivision', menu: 'Vista', label: 'Cerrar división del área de trabajo',
          run: () => window.workArea && window.workArea.cerrarDivision() },
        { id: 'vista.cerrarPestana', menu: 'Vista', label: 'Cerrar pestaña de trabajo', accel: 'Ctrl+Alt+W',
          run: () => window.workArea.cerrar(window.workArea.activa) },
        { id: 'vista.ajusteLinea', menu: 'Vista', label: 'Ajuste de línea', accel: 'Alt+Z', separadorAntes: true,
          marcado: () => ide() && ide().estadoVista('ajusteLinea'),
          run: () => ide().alternarVista('ajusteLinea') },
        { id: 'vista.minimapa', menu: 'Vista', label: 'Minimapa',
          marcado: () => ide() && ide().estadoVista('minimapa'),
          run: () => ide().alternarVista('minimapa') },
        { id: 'vista.espacios', menu: 'Vista', label: 'Mostrar espacios en blanco',
          marcado: () => ide() && ide().estadoVista('espacios'),
          run: () => ide().alternarVista('espacios') },
        { id: 'vista.guias', menu: 'Vista', label: 'Guías de sangría',
          marcado: () => ide() && ide().estadoVista('guias'),
          run: () => ide().alternarVista('guias') },
        { id: 'vista.numerosLinea', menu: 'Vista', label: 'Números de línea',
          marcado: () => ide() && ide().estadoVista('numeros'),
          run: () => ide().alternarVista('numeros') },
        { id: 'vista.encabezadosFijos', menu: 'Vista', label: 'Encabezados fijos al desplazar',
          marcado: () => ide() && ide().estadoVista('fijos'),
          run: () => ide().alternarVista('fijos') },
        { id: 'vista.letraMas', menu: 'Vista', label: 'Aumentar tamaño de letra', accel: 'Ctrl+=', separadorAntes: true,
          run: () => ide().tamanoLetra(+1) },
        { id: 'vista.letraMenos', menu: 'Vista', label: 'Reducir tamaño de letra', accel: 'Ctrl+-',
          run: () => ide().tamanoLetra(-1) },
        { id: 'vista.letraNormal', menu: 'Vista', label: 'Restablecer tamaño de letra', accel: 'Ctrl+0',
          run: () => ide().tamanoLetra(0) },
        { id: 'vista.pantallaCompleta', menu: 'Vista', label: 'Pantalla completa', accel: 'F11', separadorAntes: true,
          run: () => ide().pantallaCompleta() },
        { id: 'vista.barraEstado', menu: 'Vista', label: 'Barra de estado',
          marcado: () => !(document.getElementById('prig-estado') || {}).hidden,
          run: () => ide().alternarBarraEstado() },
        { id: 'vista.zen', menu: 'Vista', label: 'Modo concentración', accel: 'Ctrl+K Z',
          marcado: () => !!(window.layoutMgr && window.layoutMgr.zen),
          run: () => window.layoutMgr.alternarZen() },
        { id: 'vista.masTransparencia', menu: 'Vista', label: 'Más transparencia', accel: 'Ctrl+Alt+Down', separadorAntes: true,
          run: () => window.aparienciaMgr.ajustarOpacidad(-0.05) },
        { id: 'vista.menosTransparencia', menu: 'Vista', label: 'Menos transparencia', accel: 'Ctrl+Alt+Up',
          run: () => window.aparienciaMgr.ajustarOpacidad(+0.05) },

        // ---------------- Ir ----------------
        { id: 'ir.archivo', menu: 'Ir', label: 'Ir a archivo…', accel: 'Ctrl+P',
          run: () => ide().irAArchivo() },
        { id: 'ir.pestana', menu: 'Ir', label: 'Ir a pestaña abierta…', accel: 'Ctrl+K Ctrl+P',
          run: () => ide().irAPestana() },
        { id: 'ir.linea', menu: 'Ir', label: 'Ir a línea / columna…', accel: 'Ctrl+G',
          run: accion('editor.action.gotoLine') },
        { id: 'ir.simbolo', menu: 'Ir', label: 'Ir a símbolo del archivo…', accel: 'Ctrl+Shift+O',
          run: accion('editor.action.quickOutline') },
        { id: 'ir.definicion', menu: 'Ir', label: 'Ir a la definición', accel: 'F12', cuando: 'editor', separadorAntes: true,
          run: accion('editor.action.revealDefinition') },
        { id: 'ir.referencias', menu: 'Ir', label: 'Ver referencias', accel: 'Shift+F12', cuando: 'editor',
          run: accion('editor.action.goToReferences') },
        { id: 'ir.corchete', menu: 'Ir', label: 'Ir al corchete correspondiente', accel: 'Ctrl+Alt+B', cuando: 'editor',
          run: accion('editor.action.jumpToBracket') },
        { id: 'ir.atras', menu: 'Ir', label: 'Atrás', accel: 'Alt+Left', separadorAntes: true,
          run: () => ide().navegar(-1) },
        { id: 'ir.adelante', menu: 'Ir', label: 'Adelante', accel: 'Alt+Right',
          run: () => ide().navegar(+1) },
        { id: 'ir.siguienteProblema', menu: 'Ir', label: 'Siguiente problema', accel: 'F8', separadorAntes: true,
          run: accion('editor.action.marker.next') },
        { id: 'ir.anteriorProblema', menu: 'Ir', label: 'Problema anterior', accel: 'Shift+F8',
          run: accion('editor.action.marker.prev') },
        { id: 'ir.problemas', menu: 'Ir', label: 'Lista de problemas del archivo…', accel: 'Ctrl+Shift+M',
          run: () => ide().listaProblemas() },
        { id: 'ir.siguientePestana', menu: 'Ir', label: 'Pestaña siguiente', accel: 'Ctrl+PageDown', separadorAntes: true,
          run: () => ide().cambiarPestana(+1) },
        { id: 'ir.anteriorPestana', menu: 'Ir', label: 'Pestaña anterior', accel: 'Ctrl+PageUp',
          run: () => ide().cambiarPestana(-1) },

        // ---------------- Ejecutar ----------------
        { id: 'ejecutar.archivo', menu: 'Ejecutar', label: 'Ejecutar archivo', accel: 'Ctrl+Enter',
          run: () => app().runCode() },
        { id: 'ejecutar.seleccion', menu: 'Ejecutar', label: 'Ejecutar selección o línea actual', accel: 'F9',
          run: () => ide().ejecutarSeleccion() },
        { id: 'ejecutar.detener', menu: 'Ejecutar', label: 'Detener ejecución', accel: 'Ctrl+Shift+C',
          run: () => app().cancelRun() },
        { id: 'ejecutar.celda', menu: 'Ejecutar', label: 'Ejecutar celda activa', accel: 'Shift+Enter', separadorAntes: true,
          run: () => window.notebookMgr.runSingleCell(window.notebookMgr.celdaActiva || 0) },
        { id: 'ejecutar.todasCeldas', menu: 'Ejecutar', label: 'Ejecutar todas las celdas', accel: 'Ctrl+Shift+Enter',
          run: () => window.notebookMgr.runAllCells() },
        { id: 'ejecutar.reiniciarKernel', menu: 'Ejecutar', label: 'Reiniciar intérprete', accel: 'Ctrl+Alt+K',
          run: () => window.notebookMgr.restartSession() },
        { id: 'ejecutar.limpiarConsola', menu: 'Ejecutar', label: 'Limpiar consola', accel: 'Ctrl+K Ctrl+L', separadorAntes: true,
          run: () => window.terminalMgr.clear() },

        // ---------------- Secciones ----------------
        // Grupo 1: Inicio, Perfil, Biblioteca, Desafíos, Diagramas, Papers, Agenticos
        { id: 'herr.inicio', menu: 'Secciones', label: 'Inicio', accel: 'Alt+Home',
          run: () => window.Inicio && window.Inicio.abrir() },
        { id: 'herr.perfil', menu: 'Secciones', label: 'Perfil', accel: 'Ctrl+4',
          run: () => window.workArea.abrirHerramienta('modal-perfil', 'Perfil', 'fa-chart-pie') },
        { id: 'herr.biblioteca', menu: 'Secciones', label: 'Biblioteca', accel: 'Ctrl+1',
          run: () => window.workArea.abrirHerramienta('modal-book-library', 'Biblioteca', 'fa-book-bookmark') },
        { id: 'herr.practica', menu: 'Secciones', label: 'Desafíos', accel: 'Ctrl+3',
          run: () => window.Desafios && window.Desafios.abrir() },
        { id: 'herr.diagramas', menu: 'Secciones', label: 'Diagramas', accel: 'Ctrl+Alt+D',
          run: () => { window.workArea.abrirHerramienta('modal-seguimiento', 'Aprendizaje Guiado', 'fa-route'); if (window.cambiarPestanaAprendizaje) window.cambiarPestanaAprendizaje('diagramas'); } },
        { id: 'herr.papers', menu: 'Secciones', label: 'Papers', accel: 'Ctrl+Alt+P',
          run: () => { window.workArea.abrirHerramienta('modal-seguimiento', 'Aprendizaje Guiado', 'fa-route'); if (window.cambiarPestanaAprendizaje) window.cambiarPestanaAprendizaje('papers'); } },
        { id: 'herr.agentes', menu: 'Secciones', label: 'Agenticos', accel: 'Ctrl+6',
          run: () => window.workArea.abrirHerramienta('modal-agent-workflow', 'Agenticos', 'fa-diagram-project') },

        // Grupo 2: Kaggle, GitHub, YouTube
        { id: 'herr.kaggle', menu: 'Secciones', label: 'Kaggle', accel: 'Ctrl+5', separadorAntes: true,
          run: () => window.KaggleLector ? window.KaggleLector.abrir() : (window.workArea && window.workArea.abrirHerramienta('modal-kaggle-hub', 'Kaggle', 'fa-brands fa-kaggle')) },
        { id: 'herr.github', menu: 'Secciones', label: 'GitHub', accel: 'Ctrl+Shift+G',
          run: () => window.GitHubLector && window.GitHubLector.abrir() },
        { id: 'herr.youtube', menu: 'Secciones', label: 'YouTube', accel: 'Ctrl+Shift+Y',
          run: () => window.YouTubeHub && window.YouTubeHub.abrir() },

        // Grupo 3: Modelos, Gestión de modelos, Gestión Ollama, Gestión máquina
        { id: 'herr.modelos', menu: 'Secciones', label: 'Modelos', separadorAntes: true,
          run: () => window.Modelos && window.Modelos.abrir() },
        { id: 'herr.buscarModelos', menu: 'Secciones', label: 'Gestión de modelos', accel: 'Ctrl+K Ctrl+M',
          run: () => window.Modelos && window.Modelos.abrir('buscar') },
        { id: 'herr.modelosServidor', menu: 'Secciones', label: 'Gestión Ollama',
          run: () => window.Modelos && window.Modelos.abrir('servidor') },
        { id: 'herr.temperaturas', menu: 'Secciones', label: 'Gestión máquina',
          run: () => window.Temperaturas && window.Temperaturas.abrir() },

        // Comandos auxiliares disponibles por atajo y paleta
        { id: 'herr.guiado', menu: null, label: 'Aprendizaje Guiado', accel: 'Ctrl+2',
          run: () => window.workArea.abrirHerramienta('modal-seguimiento', 'Aprendizaje Guiado', 'fa-route') },
        { id: 'herr.mlflow', menu: null, label: 'Analizador de flujo ML', accel: 'Ctrl+7',
          run: () => window.workArea.abrirHerramienta('modal-ml-flow', 'Flujo ML', 'fa-project-diagram') },
        { id: 'herr.note', menu: null, label: 'Bloc de notas', accel: 'Ctrl+8',
          run: () => window.openNoteWindow() },
        { id: 'herr.encontrarModelo', menu: null, label: 'Encontrar un modelo por nombre o enlace…',
          run: async () => { if (!window.Modelos) return; await window.Modelos.abrir('buscar'); const c = document.getElementById('bm-loc'); if (c) { c.focus(); c.select(); } } },

        // ---------------- Configuración ----------------
        { id: 'config.general', menu: 'Configuración', label: 'Configuración global…', accel: 'Ctrl+,',
          run: () => window.openGlobalConfigModal('ai') },
        { id: 'config.apariencia', menu: 'Configuración', label: 'Apariencia y transparencia…', accel: 'Ctrl+Shift+A',
          run: () => window.openGlobalConfigModal('apariencia') },
        { id: 'config.atajos', menu: 'Configuración', label: 'Atajos de teclado…', accel: 'Ctrl+K Ctrl+S',
          run: () => window.openGlobalConfigModal('atajos') },
        { id: 'config.modelos', menu: 'Configuración', label: 'Modelos: ajustes, prueba y servidor…', accel: 'Ctrl+9', separadorAntes: true,
          run: () => window.Modelos && window.Modelos.abrir() },
        { id: 'config.ia', menu: 'Configuración', label: 'Descargar modelos y configuración de IA…',
          run: () => window.openGlobalConfigModal('ai') },
        { id: 'config.recomendado', menu: 'Configuración', label: 'Recursos: configuración recomendada…',
          run: () => window.Recursos && window.Recursos.abrir('tutor') },
        { id: 'config.editor', menu: 'Configuración', label: 'Editor…',
          run: () => window.openGlobalConfigModal('editor') },
        { id: 'config.sangria', menu: 'Configuración', label: 'Sangría del archivo…', separadorAntes: true,
          run: () => ide().elegirSangria() },
        { id: 'config.finLinea', menu: 'Configuración', label: 'Fin de línea del archivo (LF / CRLF)…',
          run: () => ide().elegirFinDeLinea() },
        { id: 'config.lenguaje', menu: 'Configuración', label: 'Lenguaje del archivo…',
          run: () => ide().elegirLenguaje() },

        // ---------------- Ayuda ----------------
        { id: 'ayuda.atajos', menu: 'Ayuda', label: 'Referencia de atajos de teclado', accel: 'Ctrl+K Ctrl+R',
          run: () => window.openGlobalConfigModal('atajos') },
        { id: 'ayuda.paleta', menu: 'Ayuda', label: 'Mostrar todos los comandos', accel: 'F1',
          run: () => window.menuBar.abrirPaleta() },
        { id: 'ayuda.eventos', menu: 'Ayuda', label: 'Registro de eventos del sistema…', separadorAntes: true,
          run: () => ide().registroEventos() },
        { id: 'ayuda.recargar', menu: 'Ayuda', label: 'Recargar ventana', accel: 'Ctrl+Shift+R',
          run: () => ide().recargar() },
        { id: 'ayuda.acerca', menu: 'Ayuda', label: 'Acerca de Prig IDE', separadorAntes: true,
          run: () => ide().acercaDe() },
    ];

    const porId = {};
    const ALIASES = {
        'sec.inicio': 'herr.inicio',
        'sec.perfil': 'herr.perfil',
        'sec.biblioteca': 'herr.biblioteca',
        'sec.desafios': 'herr.practica',
        'sec.diagramas': 'herr.diagramas',
        'sec.papers': 'herr.papers',
        'sec.agenticos': 'herr.agentes',
        'sec.kaggle': 'herr.kaggle',
        'sec.github': 'herr.github',
        'sec.youtube': 'herr.youtube',
        'sec.modelos': 'herr.modelos',
        'sec.gestionModelos': 'herr.buscarModelos',
        'sec.gestionOllama': 'herr.modelosServidor',
        'sec.gestionMaquina': 'herr.temperaturas',
    };
    COMANDOS.forEach(c => { c.run = seguro(c.run); porId[c.id] = c; });
    Object.entries(ALIASES).forEach(([alias, id]) => {
        if (porId[id] && !porId[alias]) porId[alias] = porId[id];
    });

    window.PrigCommands = {
        MENUS: ['Archivos', 'Edición', 'Selección', 'Vista', 'Ir', 'Ejecutar', 'Secciones', 'Configuración', 'Ayuda'],
        todos: () => COMANDOS,
        porMenu: (menu) => COMANDOS.filter(c => c.menu === menu),
        get: (id) => porId[id],
        ejecutar: (id) => { const c = porId[id]; if (c) c.run(); },
    };
})();
